# Generated by Django 5.2.3 on 2025-06-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_planner', '0002_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who created this destination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_destinations', to=settings.AUTH_USER_MODEL),
        ),
    ]
